version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - 3002:3002
    volumes:
      - .:/app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: api
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning --requirepass 3v1sWlMoj6DQTxn4e8pid0eupvwHuDjZfjsUteBupyAD1GruB6ORLSjm8k4rpFPLOdV26KVedcl/YrXl

